CREATE TABLE jw193055.DAY_WORKED
(
    Employee_id INT NOT NULL,
    Start_date DATE NOT NULL,
    Day_num INT NOT NULL CONSTRAINT CK_DAY_WORKED_DAY CHECK (Day_num > 0 AND Day_num < 15),
    CONSTRAINT FK_DAY_WORKED_TIMESHEET FOREIGN KEY(Employee_id, Start_date) REFERENCES jw193055.TIMESHEET(Employee_id, Start_date) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT PK_DAY_WORKED PRIMARY KEY (Employee_id, Start_date, Day_num),
);