CREATE TABLE jw193055.DAY_AVAL
(
    Employee_id INT NOT NULL CONSTRAINT FK_DAY_AVAL_EMPLOYEE FOREIGN KEY(Employee_id) REFERENCES jw193055.EMPLOYEE(Employee_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Day_num INT NOT NULL CONSTRAINT CK_DAY_AVAL_NUM CHECK(Day_num > 0 AND Day_num < 8 ),
    CONSTRAINT PK_DAY_AVAL PRIMARY KEY (Employee_id, Day_num),
);