CREATE TABLE jw193055.INVOICE
(
    Invoice_id INT IDENTITY(1,1) CONSTRAINT PK_INVOICE PRIMARY KEY,
    Street_address VARCHAR(100) NOT NULL,
    City VARCHAR(35) NOT NULL,
    State CHAR(2) NOT NULL,
    Zip_code CHAR(5) NOT NULL,
    Invoice_date DATE NOT NULL,
    Invoice_paid BIT NOT NULL CONSTRAINT DF_INVOICE_ISPAID DEFAULT 0,
    Customer_id INT NOT NULL CONSTRAINT FK_INVOICE_CUSTOMER FOREIGN KEY(Customer_num) REFERENCES jw193055.CUSTOMER(Customer_id),
);