CREATE TABLE jw193055.IS_ASSIGNED
(
    Job_id INT NOT NULL CONSTRAINT FK_IS_ASSIGNED_JOB FOREIGN KEY(Job_id) REFERENCES jw193055.JOB(Job_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Assignment_id INT NOT NULL CONSTRAINT FK_IS_ASSIGNED_ASSIGNMENT FOREIGN KEY(Assignment_id) REFERENCES jw193055.ASSIGNMENT(Assignment_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT PK_IS_ASSIGNED PRIMARY KEY (Job_id),
);