CREATE TABLE jw193055.PREFORMED
(
    Invoice_id INT NOT NULL CONSTRAINT FK_PREFORMED_INVOICE FOREIGN KEY(Invoice_id) REFERENCES jw193055.INVOICE(Invoice_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Service_name VARCHAR(100) NOT NULL CONSTRAINT FK_PREFORMED_SERVICE FOREIGN KEY(Service_name) REFERENCES jw193055.SERVICE(Service_name) ON UPDATE CASCADE ON DELETE CASCADE,
    Service_price DECIMAL(14, 2) NOT NULL CONSTRAINT CK_PREFORMED_PRICE CHECK(Service_price >= 0),
    CONSTRAINT PK_PREFORMED PRIMARY KEY (Invoice_id, Service_name),
);
