CREATE TABLE jw193055.QUOTED 
(
    Quote_id INT NOT NULL CONSTRAINT FK_QUOTED_QUOTE FOREIGN KEY(Quote_id) REFERENCES jw193055.QUOTE(Quote_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Service_name VARCHAR(100) NOT NULL CONSTRAINT FK_QUOTED_SERVICE FOREIGN KEY(Service_name) REFERENCES jw193055.SERVICE(Service_name) ON UPDATE CASCADE ON DELETE CASCADE,
    Service_price DECIMAL(14, 2) NOT NULL CONSTRAINT CK_QUOTED_PRICE CHECK(Service_price >= 0),
    Service_approved BIT NOT NULL CONSTRAINT DF_QUOTED_ISAPPROVED DEFAULT 0,
    CONSTRAINT PK_QUOTED PRIMARY KEY (Quote_id, Service_name),
);