CREATE TABLE jw193055.TAKES
(
    Assignment_id INT NOT NULL CONSTRAINT FK_TAKES_ASSIGNMENT FOREIGN KEY(Assignment_id) REFERENCES jw193055.ASSIGNMENT(Assignment_id) ON UPDATE CASCADE ON DELETE CASCADE,
    VIN_num CHAR(17) NOT NULL CONSTRAINT FK_TAKES_VEHICLE FOREIGN KEY(VIN_num) REFERENCES jw193055.VEHICLE(VIN_num) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT PK_TAKES PRIMARY KEY (Assignment_id, VIN_num),
);