CREATE TABLE jw193055.TIMEOFF
(
    Employee_id INT NOT NULL CONSTRAINT FK_TIMEOFF_EMPLOYEE FOREIGN KEY(Employee_id) REFERENCES jw193055.EMPLOYEE(Employee_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Start_date DATE NOT NULL,
    End_date DATE NOT NULL,
    Approved BIT NOT NULL CONSTRAINT DF_TIMEOFF_ISAPPROVED DEFAULT 0,
    CONSTRAINT PK_TIMEOFF PRIMARY KEY (Employee_id, Start_date),
);