CREATE TABLE jw193055.TIMESHEET
(
    Employee_id INT NOT NULL CONSTRAINT FK_TIMESHEET_EMPLOYEE FOREIGN KEY(Employee_id) REFERENCES jw193055.EMPLOYEE(Employee_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Start_date DATE NOT NULL,
    End_date DATE NOT NULL,
    CONSTRAINT PK_TIMESHEET PRIMARY KEY (Employee_id, Start_date),
);