CREATE TABLE jw193055.USES
(
    Job_id INT NOT NULL CONSTRAINT FK_USES_JOB FOREIGN KEY(Job_id) REFERENCES jw193055.JOB(Job_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Equip_id INT NOT NULL CONSTRAINT FK_USES_EQUIP FOREIGN KEY(Equip_id) REFERENCES jw193055.SPECIAL_EQUIP(Equip_id) ON UPDATE CASCADE ON DELETE CASCADE,
    Equip_amount INT NOT NULL CONSTRAINT CK_USES_AMOUNT CHECK (Equip_amount >= 0),
    CONSTRAINT PK_USES PRIMARY KEY (Job_id, Equip_id),
);